name: foss4g2019oceania
channels:
  - conda-forge
dependencies:
  - boto3==1.10.*
  - gmt==6.0.0
  - jupyterlab==1.2.*
  - laspy==1.6.*
  - lastools==20171231
  - numpy==1.16.*
  - pip==19.*
  - rasterio==1.1.*
  - rioxarray==0.0.*
  - scikit-image==0.16.*
  - pip:
    - https://github.com/GenericMappingTools/pygmt/archive/foss4g2019oceania.zip
