name: foss4g2019oceania
channels:
  - conda-forge
dependencies:
  - gmt==6.0.0
  - jupyterlab==1.2.*
  - pip==19.*
  - rasterio==1.1.*
  - pip:
    - https://github.com/GenericMappingTools/pygmt/archive/master.zip
